### ISSUE TITLE
I think the albums' pictures and the background should be different

### ISSUE THREAD

**Issue by cuteSakuraHime** [peinhu/AetherPlayer#4]
If you use 16:9 picture you will find the album is very Strange
And I think it is better to use different two picture.
It will be nice!
:)

**Comment by peinhu** [comment]
我用中文回答吧。  
你说的奇怪应该指的是背景图片显示不正常？因为背景图片选择的是完全适配屏幕尺寸，所以不可避免的需要拉伸，所以就造成了比例失真，如果不拉伸，那就只能选择平铺，就是多张相同图片铺满整个背景，相比这个我还是觉得拉伸好。  
关于你说的应该使用两张不同的图片，这个是可以改的，哪怕你背景一直是同一张图片也行。
