### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by cuteSakuraHime** [peinhu/AetherPlayer#5]
![CSS](http://moefq.com/images/2015/11/28/6cbfc741bbf885e89ff9ee038bf62b61.png)

iPhone6S iOS9.1

CSS貌似在手机端上支持不好？
能否进行改进？:)

**Comment by peinhu** [comment]
好的，我来解释一下为什么在手机端显示有问题。  
AetherPlayer本身只是左下角的那个小东西，后来做了一个demo展示页面，觉得只有左下角那个东西就太单调了，于是就随便弄了一个现在这样的背景特效。但是很意外，没想到有人会中意这个特效。现在的情况是AetherPlayer自身还没有对移动端做任何兼容修改，更别说这个demo展示页面了，所有CSS样式都是根据PC端屏幕设计，所以移动端样式出现异常是肯定的事。  
那么为什么AetherPlayer没有兼容移动端呢？这个也是我一直想要做的事，但是兼容移动端主要的问题是界面展现形式跟PC端是否要一致？因为移动端是没有PC上的（鼠标）悬停事件的，只有点击和滑动事件，这就造成了操作跟PC端不一致，用户体验也不同，所以我一直在思考是否把原来PC端的悬停移出改成移动端的滑动移出（感觉点击移出不太友好）？或者是在移动端完全用另一套跟PC端不一样的界面？这个都是在考虑中，如果抛开这个单纯为兼容移动端而兼容，是非常简单的一件事：）  
等我决定了移动端兼容的方式，应该很快就能实现，包括这个demo页面。关于我上边说的移动端展现的两种方式，如果你有什么想法也可以提出来一起讨论。

**Comment by peinhu** [comment]
AetherPlayer现已支持移动端
